# Generated by Django 3.0.8 on 2020-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_doctor_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_Disease',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_Disease',
            field=models.CharField(default='sick', max_length=200),
        ),
    ]
